### ISSUE TITLE
Lame Votes Not Showing Up On Initial Vote

### ISSUE THREAD

**Issue by pixelyunicorn** [Frick/ttplus#10]
I have noticed that when you lame a song before you awesome a song (after a song starts playing), your name doesn't turn red in the user list.

**Comment by Frick** [comment]
This is something that Turntable changed some time ago.  All initial lame votes are anonymous from the server (there's no way for me to access who lamed).  It is only those that awesome and then lame that will show up as it has to tell the UI to stop the user's avatar from bobbing their head.

From Turntable's Twitter account (2011/10/05): "Don't like the song playing? Lame votes are now anonymous to protect the innocent"
