### ISSUE TITLE
Underpowered PC mode

### ISSUE THREAD

**Issue by dotproto** [Frick/ttplus#15]
Add an option that would allow TT to perform better on underpowered PCs. Potential features of this mode include: 
- Disable head bob on awesome
  - Awesomes would either have no visual appearance, or avatars may change color to indicate awesome/lame.
- Simple avatar mode
  - Everyone goes ginger (or uses another single avatar)
- Disable chat bubbles on the dance floor.
  - Chat would only take place in the chat pane.
- Empty dance floor
  - Only render the DJs and the DJ booth.

For the super daring implementation, text adventure mode!
- Black background, white text.
- Pseudo CLI input.
- Basic commands such as: djs (lists djs), look at room (current room info), look at &lt;user> (user info), look at decks (lists current DJs, song info (current song ID3 info), etc.
- Chat by typing "say &lt;words>"
- Have north, south, east, west map to other rooms.
- Travel between rooms by typing "go north", etc.
- I don't actually think this is a great idea, but it is funny.

**Comment by jlbruno** [comment]
Just a heads up that the extension ttTools does include an option to turn off the avatar animation, which helps if it's using too much CPU power. 
https://github.com/egeste/ttTools

**Comment by dotproto** [comment]
Thanks for the heads up @jlbruno. There are also some scripts out there that do the same thing. It just seems like a good fit for TT+ :smile:

**Comment by Frick** [comment]
You'll note in the ttTools source that the functionality was even copied from a script I wrote.  :-)  Nevertheless, it is finally a part of TT+ in the latest release.

Edit: Nevermind... I guess he never credited me.  :-/  I did the work in figuring out what it would take to kill CPU usage and turned it into a script, he did the work to re-enable everything once it was off.
