### ISSUE TITLE
Return double-click to @-addressing

### ISSUE THREAD

**Issue by Morgon** [Frick/ttplus#18]
In all previous versions of TTPlus, double-clicking a name would automatically @-address them in chat. This is a great shortcut when someone has a fairly unwieldy name, or one that's too close to another's for Turntable's half-baked user tab-complete.

Since I would assume that someone would be more apt to @-address someone in chat rather than PM them, could we return the functionality and simply have another icon in the single-click list?

**Comment by dotproto** [comment]
@Frick can confirm, but I believe this functionality was changed when Turntable.fm added private message support. For the most part TT+ complements TT, not supersede it. That said, TT+ could _potentially_ allow users to specify double-click behavior in the options menu.

Unless other users request this feature, it will be a low priority request.

**Comment by Frick** [comment]
Agreed, @simeonv.  I have found a lot of users utilize the double-click to PM where they did not ever use double-click to @-mention.  That combined with the ease of typing @ and auto-completion makes this a very low priority.  I'll let it open as a feature request, however.  Specifically for the ability to toggle what action you'd like to happen upon double-click in the preferences.
