### ISSUE TITLE
Notifications Not Working in 0.1.2

### ISSUE THREAD

**Issue by BruceChoi** [Frick/ttplus#21]
The following popup notifications (that I have turned on) are not working for me:
Keyword mention
Open DJ spot

**Comment by kenderbard** [comment]
Have no problems with keyword mention, but do not receive vote notifications for awesomes.

**Comment by BruceChoi** [comment]
Reinstalling ttplus fixed the keyword mention for me.

**Comment by Frick** [comment]
Forgot to update these, but both should be fixed in the latest release!
