### ISSUE TITLE
Voting Notifications

### ISSUE THREAD

**Issue by kenderbard** [Frick/ttplus#26]
I have a very unique and strange problem. I receive notifications with no problem at all for everything -except- vote messages.

I have tried everything I can think of; I've uninstalled and reinstalled the addon, I've uninstalled all OTHER extensions to make sure there is no conflict. I've completely cleared browsing data. I've made certain notifications are allowed in my Under the Hood stuff. I'm at my wits end here! There's no reason for this behavior, and it seems really strange that the only thing not working are the vote messages!

**Comment by Frick** [comment]
This has been fixed and will be released soon in the 2.6 beta.  Hopefully I can get some code wrapped up in the next week to make the beta public.
