### ISSUE TITLE
manifest version 2

### ISSUE THREAD

**Issue by alok0** [Frick/ttplus#32]
Soon chrome will not allow manifest version 1 anymore.
I am having trouble installing the .crx file as well, not sure if it is related.
![](http://i.imgur.com/9ospN.png)

I am on beta channel, chrome 21.

**Comment by Frick** [comment]
I've updated the manifest in version 0.2.14.  Go ahead and grab the latest update from http://turntableplus.fm and let me know if it resolves your issues.  Thanks!
