### ISSUE TITLE
TT+ Completely Broken after TT update today

### ISSUE THREAD

**Issue by tropicanajones** [Frick/ttplus#33]
TT+ doesn't load at all after today's update rolled out by TT. 

I've tried disabling and re-enabling, uninstall and re-install.  I can see it's installed on Chrome but it's as if I'm viewing turntable.fm without the extension at all.

**Comment by Frick** [comment]
Did this clear itself up?  I've heard from a few people that they were having the same issues, but they all seem to have cleared it up by lots of re-installing, refreshing or restarting.  :-/  The code change is INCREDIBLY minor, but for some reason it seems to have a hard time taking affect.
