### ISSUE TITLE
User list missing

### ISSUE THREAD

**Issue by TheSquirrelfish** [Frick/ttplus#34]
Fired up Chrome with TT+ this morning and there was no user list
Tried disabling TT+ and reenabling
Tried restarting Chrome
Tried removing and reinstalling tt+

Saw the following errors in the console
Failed to load resource: the server responded with a status of 418 (Unknown) http://d1bw0qpdrmjlhz.cloudfront.net/4f7807cfaaa5cd175d00382cSeg1342725079
Port error: Could not establish connection. Receiving end does not exist. miscellaneous_bindings:232
Port error: Could not establish connection. Receiving end does not exist.

**Comment by TheSquirrelfish** [comment]
(I also have TT extended & TT playlist manager)

**Comment by Frick** [comment]
The port errors seem related to communications with the TT+ backend, but that error is usually caused with trying to reload the extension without refreshing the page.  The latest update (0.2.15) is available on http://turntableplus.fm.  See if upgrading and performing a (hard) refresh or 3 doesn't do the trick.  Thanks!
