### ISSUE TITLE
Adding a 'Get my music back!' button

### ISSUE THREAD

**Issue by Morgon** [Frick/ttplus#40]
As we all know, Turntable has a notorious issue with losing sound. Through some digging, I was able to find some JS commands that usually get it back without having to refresh. Adding this to TurntablePlus may not be the best solution (i.e. fixing it on the TT side would be best ;) ), but it would be a nice stop-gap.

Since TTP grabs the obfuscated room object, it's as easy as calling
ttp.roominfo.scheduleResyncStream()

Having a button on the UI might help people who are affected by the occasional drop.

**Comment by Frick** [comment]
We have officially tweaked the streaming code - this should hopefully not be needed any longer!
