### ISSUE TITLE
Latest update sucks!

### ISSUE THREAD

**Issue by MikeWills** [Frick/ttplus#43]
The chat and queues drop way below the screen and don't remember where I put them. I would rather have an option if I want to be able to move them or not. I liked the previous version much better to be honest.

**Comment by MikeWills** [comment]
Also I have to refresh several times before I can start interacting with the site sometimes.

**Comment by Frick** [comment]
What screen resolution are you running?  I haven't had a chance to play with it on any small screens yet, but I can imagine there may be an issue there.  If you can provide a few things, that will greatly help me to fix the issue.
- screen resolution
- window resolution: `$(window).width() + 'x' + $(window).height()`
- saved layouts: `ttp.send({get:'preferences'},function(a){console.log(a.layout);});`
- a screenshot of the messed up layout

**Comment by MikeWills** [comment]
- 1280x1024
- $(window).width() + 'x' + $(window).height() "1263x545"
- ttp.send({get:'preferences'},function(a){console.log(a.layout);});
  2
  Object {1263x922: Object, 1280x922: Object, 1263x939: Object, 1280x939: Object}

I can't do a screen shot right now. The queue and chat were about 3-4 inches down underneath the bottom of the screen. I had to scroll down and move them up, resize them to the right size.  The chat I had to resize before I could even move it. Then they are on top of other overlays. 

I would love an option to revert back to just using the chat and queue like TT delivers them. Really i am using your plugin for the highlighting of lames and awesomes and showing the real-time count. That is all I really want.

**Comment by Frick** [comment]
Sorry, can you do this instead:
- ttp.send({get:'preferences'},function(a){console.log(JSON.stringify(a.layout));});

I may add an option to disable the layout functionality, but it won't be today.  Ideally, I'd like to simply fix the layout issue so that you don't even have to think about it... if you want to move things around, you can with ease, otherwise it _should_ behave as "stock" Turntable does.  There is one layout bug with the chat ding overlay winding up behind the chat pane, but that will be fixed in an update later today.

**Comment by MikeWills** [comment]
ttp.send({get:'preferences'},function(a){console.log(JSON.stringify(a.layout));});
3
{"1263x939":{"left":{"top":449,"left":934,"width":256,"height":773},"right":{"top":0,"left":972,"width":291,"height":110}},"1280x939":{"left":{"top":-900,"left":18,"width":256,"height":773},"right":{"top":-1673,"left":1024,"width":256,"height":774}},"1263x922":{"left":{"top":-900,"left":0,"width":256,"height":773},"right":{"top":0,"left":1024,"width":256,"height":774}},"1280x922":{"left":{"top":-751,"left":439,"width":256,"height":773},"right":{"top":-2678,"left":1121,"width":256,"height":774}}}

**Comment by Frick** [comment]
Try the latest update: https://chrome.google.com/webstore/detail/turntable-plus/icgjnmfceciegoonlpegpcaaeggghemc

It adds a resize handler to the window which may do what you're looking for.  Let me know your thoughts.

**Comment by MikeWills** [comment]
I still just want to highlight the awesomes and lames. I don't care about moving the chat and queue around. Maybe I'll have to move on to look for other options. Or just create it myself.

**Comment by Frick** [comment]
I'm sorry for the trouble, but I only have so much bandwidth.  I have a version working where it is an option, I just need to add the option to the settings page.  Of course, If you would like to create it yourself, you're more than welcome to... I open source the code for just this reason!  But if you can hold out for another day, I'd imagine I can have an update released soon.

**Comment by MikeWills** [comment]
I understand you are busy. Trust me I have a bot in beta for several months now. I can stick it out and see what you come up with.

**Comment by MikeWills** [comment]
Here is a screenshot of the frustration I have. 

http://dl.dropbox.com/u/2732434/turntable%20All%20Music%20Mix%20-%20Google%20Chrome_2012-12-04_14-04-55.png

It jumps up above the screen and I can't move it. Sometimes happens under too. No scroll bars to allow me to fix.

**Comment by Frick** [comment]
Wow... I'm really not even sure how that is happening. With the latest update I have it move the panes within the boundaries of the page, or even shrink the panes, to ensure they never get cut off... I have no idea how you wound up with negative offsets, so I'll put something in so that positioning can never be negative in the future. I'm hoping to push the update to add the preference to turn off drag/resize tonight, nevertheless.

**Comment by MikeWills** [comment]
I'll try to get screen shots of the other problems.

**Comment by Frick** [comment]
Give 0.3.6 a shot and try the option on the Misc Settings page... hopefully that will be what you're looking for.

https://chrome.google.com/webstore/detail/turntable-plus/icgjnmfceciegoonlpegpcaaeggghemc

**Comment by MikeWills** [comment]
Thank you! Thank you! Thank you!
