### ISSUE TITLE
Feature Request AutoDj

### ISSUE THREAD

**Issue by MikeWills** [Frick/ttplus#44]
It'd be sweet to have AutoDJ included into this plugin. 

Allow for and adjustable time frame (1-10 seconds) DO NOT have instant. Only try once (in case a bot boots). Kind of like Bacon Bits works.

**Comment by Frick** [comment]
This is one that you will have to do on your own.  TT+ has never had auto-DJ / auto-voting to respect the wishes of the company, and seeing how I work for the company now... it just isn't happening.  :-)

**Comment by MikeWills** [comment]
That I didn't know. Fully understandable.
