### ISSUE TITLE
Scrollbar auto scroll up with download bar

### ISSUE THREAD

**Issue by curtislarson** [Frick/ttplus#45]
When the download bar appears or disappears (through a user hitting the X button) it causes the chat scroll-bar to go all the way up to the very top. This bug does not exist when the ttplus extension is disabled leading me to believe that the extension is causing it.

**Comment by nfollin** [comment]
Yup! indeed. Stupid chrome...

**Comment by threeangrynuns** [comment]
This is not exclusive to the download bar. Other events that cause the window to resize, such as opening the chrome developer tools in docked mode, also cause the chat to scroll to the top.

**Comment by Frick** [comment]
Just wanted to say I'm aware of the issue, but haven't had a chance to look into it yet.  I'll try to tomorrow, hopefully!

**Comment by Frick** [comment]
This was finally fixed in the latest update. I'm sorry it took so long!
